version: '3.8'
services:
  tdf-trino:
    image: localhost:5000/virtru/tdf-trino:latest
    container_name: tdf-trino
    platform: linux/arm64
    restart: always
    depends_on:
      dsp:
        condition: service_healthy
        restart: true
    #command: ["trino", "--server", "trino:8080", "--catalog", "postgresql", "--schema", "public"]
    # depends_on:
    #   postgres-db:
    #     condition: service_healthy
    #     restart: true
    extra_hosts:
      local-dsp.virtru.com: "host-gateway"
    ports:
      - "28080:8080"
    volumes:
      - ./trino-config/catalog:/etc/trino/catalog
      - ./trino-config/certs:/etc/trino/certs
    # networks:
    #   - trino-network

  # postgres-db:
  #   image: postgres:latest
  #   container_name: postgres-db
  #   environment:
  #     POSTGRES_USER: trino_user
  #     POSTGRES_PASSWORD: password123
#     networks:
#       - trino-network

# networks:
#   trino-network:
#     driver: bridge