header-authenticator.name=jwt-header-auth
jwt-header-auth.oidc-jwks-url=https://local-dsp.virtru.com:8443/auth/realms/opentdf/protocol/openid-connect/certs
jwt-header-auth.principal-claim=preferred_username
jwt-header-auth.trusted-certs-directory=/etc/trino/certs
